[Web-22] add function addyear dropdown
anthopark/Anteater-Pathway pull request #58
Opened 2023-01-13 19:43 UTC by emilyPhee

https://user-images.githubusercontent.com/57051508/212405158-765e911e-8bd2-4108-ae28-bac77a5e8039.mov

- Disable option when year added
- Display the side Toast for action completion

_AppUser's years array only contains unique years value and is sorted in ascending order._

2023-01-13 19:45 UTC, emilyPhee reviewed
reviewed

2023-01-13 19:46 UTC, emilyPhee commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Web] Add functionalities to AddYearDropdown](https://trello.com/c/GLIQGbF8/22-web-add-functionalities-to-addyeardropdown)

2023-01-14 01:17 UTC, anthopark requested changes
Good work. Left a few comments to be addressed

2023-01-14 01:17 UTC, anthopark commented on new-nextjs-client/src/components/index-page/AddYearDropdown/AddYearDropdown.tsx
> +        showToastBox({
call `showToastBox()` outside the `updateAppUser()`.

updateAppUser should only include code related to updating the state of AppUser

2023-01-14 01:17 UTC, anthopark commented on new-nextjs-client/src/components/index-page/AddYearDropdown/AddYearDropdown.tsx
> +        draft.sortYear();
sortYear() shouldn't be called here. the sorting should be handled inside `addYear()` method.

2023-01-14 01:17 UTC, anthopark commented on new-nextjs-client/src/components/index-page/AddYearDropdown/AddYearDropdown.tsx
> +      const newYearOptionsArr = yearOptions.map((obj) => {
Let's make a separate helper function for this. you can name `disableSelectedOptions()` then call `setYearOptions()` inside it with the updated options.

2023-01-14 01:17 UTC, anthopark commented on new-nextjs-client/src/entities/app-user.ts
> +  sortYear: () => void;
Remove this and make it a private method. which will be only called in `addYear()`

2023-01-16 00:55 UTC, anthopark approved these changes

2023-01-16 00:56 UTC, anthopark approved these changes

2023-01-16 01:01 UTC, merged